name: "Deploy to Nuget"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_PATH: "VideoPoker.Backend/VideoPoker.Backend.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  deploy:
    name: "Deploy"
    runs-on: windows-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Install .net"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.x"

    - name: "Restore packages"
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: "Build project"
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: "Pack Project"
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: "Push Package"
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.KEY }} -s ${{ env.NUGET_SOURCE_URL }}